// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0OcctNgV22RaERZ6WxU1BnPUfH4fFiIc',
    appId: '1:649244069273:web:f3badd4aa305b2deb85708',
    messagingSenderId: '649244069273',
    projectId: 'usquttion',
    authDomain: 'usquttion.firebaseapp.com',
    databaseURL: 'https://usquttion-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'usquttion.appspot.com',
    measurementId: 'G-6LNF648K0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATflC05N8UxM6rugEFEuJiL_7y9Kp9Ffk',
    appId: '1:649244069273:android:df7f368c6220c8c2b85708',
    messagingSenderId: '649244069273',
    projectId: 'usquttion',
    databaseURL: 'https://usquttion-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'usquttion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7n8oxZXQrHJ1w4Vj1P3B7ZVhfPvdyQMw',
    appId: '1:649244069273:ios:732f4e09810d31c3b85708',
    messagingSenderId: '649244069273',
    projectId: 'usquttion',
    databaseURL: 'https://usquttion-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'usquttion.appspot.com',
    iosBundleId: 'com.example.us',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7n8oxZXQrHJ1w4Vj1P3B7ZVhfPvdyQMw',
    appId: '1:649244069273:ios:0085907baf20d6c3b85708',
    messagingSenderId: '649244069273',
    projectId: 'usquttion',
    databaseURL: 'https://usquttion-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'usquttion.appspot.com',
    iosBundleId: 'com.example.us.RunnerTests',
  );
}
